const SHARED_TIPS = {
  hydration: { icon: 'Droplets', label: 'Stay hydrated', description: 'Drink water regularly' },
  rest: { icon: 'Moon', label: 'Get rest', description: 'Allow your body to recover' },
  stretch: { icon: 'Sparkles', label: 'Stretch gently', description: 'Light movement helps' },
  heat: { icon: 'Flame', label: 'Apply heat', description: 'Warm compress for comfort' },
  cold_compress: { icon: 'Snowflake', label: 'Apply cold', description: 'Ice pack for swelling' },
  activity: { icon: 'Footprints', label: 'Stay active', description: 'Avoid prolonged bed rest' },
  sleep: { icon: 'Moon', label: 'Improve sleep', description: 'Consistent sleep schedule' },
  breathing: { icon: 'Wind', label: 'Deep breathing', description: 'Calm your nervous system' },
  screens: { icon: 'Monitor', label: 'Reduce screen time', description: 'Rest your eyes' },
  warm_drinks: { icon: 'Coffee', label: 'Warm drinks', description: 'Soothing warm liquids' },
  eat_well: { icon: 'Apple', label: 'Eat well', description: 'Balanced, nutritious meals' },
  posture: { icon: 'ArrowUp', label: 'Check posture', description: 'Sit and stand tall' },
  walking: { icon: 'Footprints', label: 'Short walks', description: 'Gentle walking helps' },
  elevate: { icon: 'ArrowUp', label: 'Elevate area', description: 'Raise above heart level' },
  humidify: { icon: 'Cloud', label: 'Humidify air', description: 'Moist air soothes airways' },
  sunshine: { icon: 'Sun', label: 'Get sunlight', description: 'Natural light boosts mood' },
  meditation: { icon: 'Brain', label: 'Meditate', description: 'Even 5 minutes helps' },
  hot_shower: { icon: 'Droplets', label: 'Hot shower', description: 'Steam helps congestion' },
};

export const LIFESTYLE_TIPS = {
  headache: [SHARED_TIPS.hydration, SHARED_TIPS.heat, SHARED_TIPS.screens, SHARED_TIPS.rest],
  migraine: [SHARED_TIPS.rest, SHARED_TIPS.screens, SHARED_TIPS.breathing, SHARED_TIPS.hydration],
  back_pain: [SHARED_TIPS.heat, SHARED_TIPS.stretch, SHARED_TIPS.activity, SHARED_TIPS.posture],
  neck_pain: [SHARED_TIPS.stretch, SHARED_TIPS.posture, SHARED_TIPS.heat, SHARED_TIPS.screens],
  muscle_pain: [SHARED_TIPS.heat, SHARED_TIPS.stretch, SHARED_TIPS.hydration, SHARED_TIPS.rest],
  cold: [SHARED_TIPS.hydration, SHARED_TIPS.rest, SHARED_TIPS.warm_drinks, SHARED_TIPS.hot_shower],
  cough: [SHARED_TIPS.hydration, SHARED_TIPS.humidify, SHARED_TIPS.rest, SHARED_TIPS.warm_drinks],
  sore_throat: [SHARED_TIPS.hydration, SHARED_TIPS.warm_drinks, SHARED_TIPS.rest, SHARED_TIPS.humidify],
  congestion: [SHARED_TIPS.hot_shower, SHARED_TIPS.humidify, SHARED_TIPS.hydration, SHARED_TIPS.elevate],
  nausea: [SHARED_TIPS.hydration, SHARED_TIPS.rest, SHARED_TIPS.breathing, SHARED_TIPS.eat_well],
  anxiety: [SHARED_TIPS.breathing, SHARED_TIPS.meditation, SHARED_TIPS.walking, SHARED_TIPS.sleep],
  stress: [SHARED_TIPS.breathing, SHARED_TIPS.meditation, SHARED_TIPS.walking, SHARED_TIPS.sunshine],
  insomnia: [SHARED_TIPS.sleep, SHARED_TIPS.screens, SHARED_TIPS.breathing, SHARED_TIPS.activity],
  fatigue: [SHARED_TIPS.hydration, SHARED_TIPS.sleep, SHARED_TIPS.activity, SHARED_TIPS.eat_well],
  joint_pain: [SHARED_TIPS.activity, SHARED_TIPS.stretch, SHARED_TIPS.heat, SHARED_TIPS.elevate],
  sinus_pressure: [SHARED_TIPS.hot_shower, SHARED_TIPS.humidify, SHARED_TIPS.elevate, SHARED_TIPS.hydration],
  toothache: [SHARED_TIPS.warm_drinks, SHARED_TIPS.rest, SHARED_TIPS.hydration],
  skin_rash: [SHARED_TIPS.hydration, SHARED_TIPS.rest],
  sunburn: [SHARED_TIPS.cold_compress, SHARED_TIPS.hydration, SHARED_TIPS.rest],
  sprain: [SHARED_TIPS.cold_compress, SHARED_TIPS.elevate, SHARED_TIPS.rest, SHARED_TIPS.activity],
  hangover: [SHARED_TIPS.hydration, SHARED_TIPS.rest, SHARED_TIPS.eat_well, SHARED_TIPS.warm_drinks],
  burnout: [SHARED_TIPS.breathing, SHARED_TIPS.meditation, SHARED_TIPS.walking, SHARED_TIPS.sleep],
  brain_fog: [SHARED_TIPS.hydration, SHARED_TIPS.breathing, SHARED_TIPS.activity, SHARED_TIPS.sunshine],
  low_energy: [SHARED_TIPS.hydration, SHARED_TIPS.eat_well, SHARED_TIPS.activity, SHARED_TIPS.sleep],
  dehydration: [SHARED_TIPS.hydration, SHARED_TIPS.rest, SHARED_TIPS.eat_well],
  period_cramps: [SHARED_TIPS.heat, SHARED_TIPS.stretch, SHARED_TIPS.rest, SHARED_TIPS.hydration],
  indigestion: [SHARED_TIPS.activity, SHARED_TIPS.rest, SHARED_TIPS.hydration],
};

export const FALLBACK_TIPS = [
  SHARED_TIPS.hydration,
  SHARED_TIPS.rest,
  SHARED_TIPS.activity,
  SHARED_TIPS.eat_well,
];
